---
title: "Milestone_3"
author: "Feven Yohannes"
date: "September 30, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
library(readr)
library(dplyr)
library(knitr)
library(ggplot2)
library(janitor)
library(gt)
library(tidyverse)
library(httr)
library(rvest)
un <- read_html("http://data.un.org/en/iso/et.html",skip=1)
tbls <- html_nodes(un, "table")
un_tbl <- un %>%
        html_nodes("table") %>%
        .[3:4] %>%
        html_table(fill = TRUE)
world_bank <- read_csv("/Users/feven/Documents/Gov1005/Final Project/API_ETH_DS2_en_csv_v2_205341.csv")

```



The first dataset that I have is from the world bank and my second data set is from the UN. Both of these sources contain some data on Ethiopia's economic and social development over the last thirty years. Ethiopia has undergone incredible economic changes over the last thirty years, and I'm interested in seeing which sectors changed the most and how the quality of life has changed. However, beyond just the economic aspect, I'm interested in analyzing the social indicators, to see if they have changed as quickly as economic factors such as GDP per capita. For example, as education increased or life expectancy. I'm hoping to uncover whether or not Ethiopia has drastically changed, and which aspects of the economy and society still need development. 
